### ISSUE TITLE
Colab link needs more info

### ISSUE THREAD

**Issue by charlesjlee** [ezzcodeezzlife/dalle2-in-python#12]
Three changes to the Colab notebook
### 1. Add instructions (same as the `README`) on how to get the session token
  >1. Go to https://labs.openai.com/
  >1. Open Network Tab in Developer Tools
  >1. Type a prompt and press "Generate"
  >1. Look for fetch to https://labs.openai.com/api/labs/tasks
  >1. In the request header look for authorization then get the Bearer Token

**Comment by ezzcodeezzlife** [comment]
removed collab link
