### ISSUE TITLE
Add support for generating variations

### ISSUE THREAD

**Issue by janek** [ezzcodeezzlife/dalle2-in-python#14]
Generate variations from an image, like in [labs.openai.com](labs.openai.com).

**Comment by kv-crosstech** [comment]
Isn't it same as #8? Name of the issue does not align, but content seems to be about variations

**Comment by ezzcodeezzlife** [comment]
oh yes indeed.. i just checked the titles 😆 will change title on #8 and close this one

**Comment by janek** [comment]
Sorry that I missed it and thanks for the cleanup :)
