### ISSUE TITLE
Downloaded images are webp not png

### ISSUE THREAD

**Issue by TillBeemelmanns** [ezzcodeezzlife/dalle2-in-python#23]
**Describe the bug**
I just ran `generate_and_download()` and noticed that the downloaded images are of type `.webp`, but they are stored as `png` images. I am not sure if openai has changed the compression type recently or if the file ending was set to `png` on purpose. However, I was confused at first when I tried to open the files with my image viewer and it could not render the images.

**To Reproduce**
run `dalle.generate_and_download()`

**Expected behavior**
The file ending should be `.webp` so that a file browser or image viewer can open the downloaded images. Opening the `.png` files with a browser worked fine ofc.

**Comment by ezzcodeezzlife** [comment]
Hey @TillBeemelmanns thanks for bringing this up. OpenAI must have changed this. Will fix asap 🚀
