### ISSUE TITLE
Incorrect API key provided: sess-xxx************xxxx

### ISSUE THREAD

**Issue by TonyZZhang** [ezzcodeezzlife/dalle2-in-python#5]
**Describe the bug**

There was a problem

![56$~TETPTCHJ}%9D QGYAZV](https://user-images.githubusercontent.com/39551789/180145220-6275b28f-73c9-4515-bb8b-23658ba70663.png)

**Comment by ezzcodeezzlife** [comment]
in the Dalle2 constructor you need to change the xxxxx to your personal bearer key. you can find a tutorial how to get it in the readme. hope this help ❤️

**Comment by TonyZZhang** [comment]
> in the Dalle2 constructor you need to change the xxxxx to your personal bearer key. you can find a tutorial how to get it in the readme. hope this help ❤️

Thank you for your reply
